catching-non-exception:27::"Catching an exception which doesn't inherit from BaseException: MyException"
catching-non-exception:33::"Catching an exception which doesn't inherit from BaseException: MyException"
catching-non-exception:33::"Catching an exception which doesn't inherit from BaseException: MySecondException"
catching-non-exception:54::"Catching an exception which doesn't inherit from BaseException: None"
catching-non-exception:54::"Catching an exception which doesn't inherit from BaseException: list()"
catching-non-exception:59::"Catching an exception which doesn't inherit from BaseException: None"
catching-non-exception:72::"Catching an exception which doesn't inherit from BaseException: 4"
catching-non-exception:72::"Catching an exception which doesn't inherit from BaseException: None"
catching-non-exception:72::"Catching an exception which doesn't inherit from BaseException: list([4, 5, 6])"
catching-non-exception:85::"Catching an exception which doesn't inherit from BaseException: NON_EXCEPTION_TUPLE"
catching-non-exception:103::"Catching an exception which doesn't inherit from BaseException: object"
catching-non-exception:108::"Catching an exception which doesn't inherit from BaseException: range"
